# Átállítja a server default portját 8000-re
# Terminalból történő idításnál is felülírható
# Környezeti változóval: SERVER_PORT-nak értéket adva
# Vagy pl. mavennel:
# mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8081"
server:
  port: 8000

logging:
  level:
    root: INFO
    hu:
      flowacademy:
        kappaspring:
          reallife: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogpost
    username: blogpost
    password: blogpost
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # create, create-drop, update, validate, none

blogpost:
  type: hash # tree or hash
